services:
  - type: web
    name: fastapi-langgraph-app
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: OPENAI_TEMPERATURE
        value: 0
      - key: OPENAI_SEED
        value: 42
      - key: APP_NAME
        value: Scenario Re-Contextualization API
      - key: APP_VERSION
        value: 1.0.0
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHON_VERSION
        value: 3.13.5
